/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EncomendasRouteImport } from './routes/encomendas'
import { Route as AdminControlRouteImport } from './routes/admin-control'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendasRoute = EncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminControlRoute = AdminControlRouteImport.update({
  id: '/admin-control',
  path: '/admin-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-control': typeof AdminControlRoute
  '/encomendas': typeof EncomendasRoute
  '/estoque': typeof EstoqueRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-control': typeof AdminControlRoute
  '/encomendas': typeof EncomendasRoute
  '/estoque': typeof EstoqueRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-control': typeof AdminControlRoute
  '/encomendas': typeof EncomendasRoute
  '/estoque': typeof EstoqueRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-control'
    | '/encomendas'
    | '/estoque'
    | '/forgot-password'
    | '/insumos'
    | '/login'
    | '/perfil'
    | '/produtos'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-control'
    | '/encomendas'
    | '/estoque'
    | '/forgot-password'
    | '/insumos'
    | '/login'
    | '/perfil'
    | '/produtos'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/admin-control'
    | '/encomendas'
    | '/estoque'
    | '/forgot-password'
    | '/insumos'
    | '/login'
    | '/perfil'
    | '/produtos'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminControlRoute: typeof AdminControlRoute
  EncomendasRoute: typeof EncomendasRoute
  EstoqueRoute: typeof EstoqueRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendas': {
      id: '/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof EncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-control': {
      id: '/admin-control'
      path: '/admin-control'
      fullPath: '/admin-control'
      preLoaderRoute: typeof AdminControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminControlRoute: AdminControlRoute,
  EncomendasRoute: EncomendasRoute,
  EstoqueRoute: EstoqueRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
